"""Extract the <main> body fragment and page metadata from every page of the
English reference mirror, so each page can be translated in isolation while the
shared chrome (head/header/footer) is regenerated by build.py.

Run once against the mirror; produces tools/en-bodies/*.html + tools/pages.json.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
MIRROR = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "en-mirror")
BODIES = os.path.join(HERE, "en-bodies")


def one(pattern, text, group=1, flags=re.S):
    m = re.search(pattern, text, flags)
    return m.group(group).strip() if m else ""


def main():
    if not os.path.isdir(MIRROR):
        raise SystemExit("mirror not found: " + MIRROR)

    pages = []
    for root, _, files in os.walk(MIRROR):
        for fn in files:
            if fn != "index.html":
                continue
            full = os.path.join(root, fn)
            rel = os.path.relpath(root, MIRROR).replace("\\", "/")
            rel = "" if rel == "." else rel + "/"

            with open(full, encoding="utf-8") as f:
                html = f.read()

            body = one(r"<main[^>]*>(.*?)</main>", html)
            if not body:
                print("  !! no <main> in", rel or "(home)")
                continue

            # Which nav item is highlighted, and any body attributes (data-spread).
            body_tag = one(r"(<body[^>]*>)", html)
            body_attrs = one(r"<body\s*([^>]*)>", body_tag) if body_tag else ""

            # Script srcs vary between absolute, root-relative and "../../"
            # forms depending on page depth, so match on the basename.
            KNOWN_JS = {"deck.js", "spreads.js", "interpretations.js", "app.js"}
            scripts = [s.split("?")[0].split("/")[-1]
                       for s in re.findall(r'<script src="([^"]+)"', html)]
            scripts = [s for s in scripts if s in KNOWN_JS]

            nav_active = one(r'<nav class="main-nav"[^>]*>.*?<a href="[^"]*"'
                             r' class="active">([^<]+)</a>', html)

            pages.append({
                "path": rel,
                "depth": rel.count("/"),
                "title": one(r"<title>(.*?)</title>", html),
                "description": one(r'<meta name="description" content="(.*?)"', html),
                "nav_active": nav_active,
                "body_attrs": body_attrs,
                "scripts": scripts,
            })

            out = os.path.join(BODIES, (rel or "home/") + "body.html")
            os.makedirs(os.path.dirname(out), exist_ok=True)
            with open(out, "w", encoding="utf-8", newline="\n") as f:
                f.write(body + "\n")

    pages.sort(key=lambda p: p["path"])
    with open(os.path.join(HERE, "pages.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump(pages, f, ensure_ascii=False, indent=2)

    print("extracted %d pages" % len(pages))
    kinds = {}
    for p in pages:
        k = p["path"].split("/")[0] or "(root)"
        kinds[k] = kinds.get(k, 0) + 1
    print("by section:", kinds)
    print("script sets:", sorted({tuple(p["scripts"]) for p in pages}))


if __name__ == "__main__":
    main()
